### ISSUE TITLE
rename repo

### ISSUE THREAD

**Issue by jacobvjk** [RMI-PACTA/pacta.aggregate.loanbook.plots#55]
suggestion: `pacta.aggregate.loanbook.plots`
This is a somewhat clunky name for a repository, but given it covers both analysis and plotting functions, it seems the most accurate name for now.

Open to other ideas @AlexAxthelm @jdhoffa @MonikaFu

**Comment by MonikaFu** [comment]
is the fact that it's `loanbook` crucial to the functionality of this package? The matching is done elsewhere, right? Basically what I'm trying to figure out is if you would have data that is not a loanbook in the right format, could you use this package and get sensible results? Because then I wouldn't put `loanbook` in the name.

**Comment by jacobvjk** [comment]
right now, all functions depend on `loanbook` format and honestly the package probably does a bit more than we would ideally want it to do. some of that is very directly related to running the analysis on loan books (e.g. `R/create_benchmark_loanbook.R`) so I think in the future, we could disentangle that in the spirit of following a micro services approach and then it would not really matter if the underlying data is a loan book or not. But at the moment it feels like a bit of a stretch.

**Comment by jacobvjk** [comment]
solved by restructuring into https://github.com/RMI-PACTA/pacta.multi.loanbook.analysis and https://github.com/RMI-PACTA/pacta.multi.loanbook.plot/issues
